### ISSUE TITLE
setting default vars with handler

### ISSUE THREAD

**Issue by wesyoung** [jeteve/Apache2--REST#1]
is there any reason you couldn't do something like this, or is there a better way to pass the dir_config variables to the topRootClass objects?

--- Apache2/REST.pm.1   2010-11-09 23:01:55.000000000 +0000
+++ Apache2/REST.pm 2010-11-09 23:08:14.000000000 +0000
@@ -292,6 +292,10 @@
     my $topHandler = $handlerRootClass->new() ;
     my $conf = Apache2::REST::Conf->new() ;
     $conf->Apache2RESTErrorOutput($r->dir_config('Apache2RESTErrorOutput') || 'both' );
-    my $vars = $r->dir_config();
-    foreach (keys %$vars){
-        $conf->{$_} = $vars->{$_};
-    }
   $topHandler->conf($conf);
  
   my @stack = split('\/+' , $uri);

**Comment by wesyoung** [comment]
http://pastebin.com/kJhe4Rqh

**Comment by jeteve** [comment]
Hi,

  I think it's not a good idea becasue this conf object is meant to disappear at some time, as it's mainly an poltergeist anti-pattern. If you want to access r->dir_config from any handler, you should use the request object like this:

```
$req->r->dir_config
```

I didn't try it yet, so tell me if it works to access your configuration variables!

Jerome.

**Comment by wesyoung** [comment]
ah. yea. that works. I was calling it as ->r() instead of ->{'r'} (which caused an r.al error.

thanks for the feedback!

this can be closed.

**Comment by jeteve** [comment]
Cool. You should even be able to call $req->dir_config directly, as A2:R::Request subclasses A2::Request according to http://httpd.apache.org/apreq/docs/libapreq2/group__apreq__xs__request.html#subclassing_apache2__request

Can you confirm?

Cheers!

**Comment by wesyoung** [comment]
huh. I coulda swore I tried that last night (must have been coding too long). Yea, that works too. Thanks!

**Comment by jeteve** [comment]
Ok nice. Closing the ticket then :)
